add_fail_unit_ – naturalFRUIT
add_fail_unit_ Subroutine
5 statements
Source File
private subroutine add_fail_unit_(unitName, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: unitName
character(len=*), intent(in) :: message
Calls
Called by
Contents
Source Code
add_fail_unit_
Source Code
  subroutine add_fail_unit_ (unitName, message)
    character (*), intent (in) :: unitName
    character (*), intent (in) :: message
    call add_fail_ ("[in " //  unitName // "(fail)]: " //  message)
  end subroutine add_fail_unit_
Call graph
add_fail_unit_ calls add_fail_
add_fail_ calls failed_assert_action
failed_assert_action calls increase_message_stack_, make_error_msg_, failed_mark_
make_error_msg_ calls strip
failed_mark_ calls output_mark_
strip calls strip_, strip_length_
addfail calls add_fail_unit_
add_fail calls add_fail_unit_