add_success – naturalFRUIT
add_success Subroutine
7 statements
Source File
public subroutine add_success()
Arguments
None
Calls
Called by
Contents
Source Code
add_success
Source Code
  subroutine add_success
    !$omp critical     (FRUIT_OMP_ADD_SUCCESS)
      successful_assert_count = successful_assert_count + 1
      last_passed = .true.
    !$omp end critical (FRUIT_OMP_ADD_SUCCESS)
    if (if_show_dots) then
      call success_mark_
    endif
  end subroutine add_success
Call graph
add_success calls success_mark_
success_mark_ calls output_mark_
assert_eq_2d_string_ calls add_success
assert_eq_real_in_range_ calls add_success
assert_not_equals_1d_real_ calls add_success
assert_not_equals_1d_logical_ calls add_success
assert_eq_2d_logical_ calls add_success
assert_eq_2d_complex_in_range_ calls add_success
assert_not_equals_2d_string_ calls add_success
assert_not_equals_1d_string_ calls add_success
assert_not_equals_complex_in_range_ calls add_success
assert_eq_1d_string_ calls add_success
assert_eq_logical_ calls add_success
assert_not_equals_2d_int_ calls add_success
assert_eq_1d_int_ calls add_success
assert_not_equals_1d_double_in_range_ calls add_success
assert_eq_1d_logical_ calls add_success
obsolete_addsuccess_ calls add_success
assert_eq_1d_double_ calls add_success
assert_not_equals_2d_double_ calls add_success
assert_eq_1d_real_ calls add_success
assert_not_equals_2d_real_in_range_ calls add_success
assert_eq_double_in_range_ calls add_success
assert_not_equals_2d_complex_ calls add_success
assert_eq_complex_ calls add_success
assert_eq_int_ calls add_success
assert_eq_2d_double_in_range_ calls add_success
assert_not_equals_string_ calls add_success
assert_eq_1d_complex_in_range_ calls add_success
assert_not_equals_int_ calls add_success
assert_not_equals_real_in_range_ calls add_success
assert_not_equals_2d_complex_in_range_ calls add_success
assert_eq_2d_real_in_range_ calls add_success
assert_not_equals_real_ calls add_success
assert_eq_1d_double_in_range_ calls add_success
assert_eq_2d_int_ calls add_success
assert_not_equals_1d_double_ calls add_success
assert_eq_2d_complex_ calls add_success
assert_not_equals_complex_ calls add_success
assert_not_equals_1d_real_in_range_ calls add_success
assert_not_equals_2d_real_ calls add_success
assert_eq_string_ calls add_success
assert_eq_complex_in_range_ calls add_success
assert_not_equals_double_ calls add_success
assert_eq_2d_real_ calls add_success
assert_eq_1d_complex_ calls add_success
assert_not_equals_2d_double_in_range_ calls add_success
assert_eq_2d_double_ calls add_success
assert_true calls add_success
assert_not_equals_2d_logical_ calls add_success
assert_not_equals_double_in_range_ calls add_success
assert_false_ calls add_success
assert_not_equals_logical_ calls add_success
assert_not_equals_1d_int_ calls add_success
assert_eq_double_ calls add_success
assert_eq_1d_real_in_range_ calls add_success
assert_not_equals_1d_complex_ calls add_success
assert_eq_real_ calls add_success
assert_not_equals_1d_complex_in_range_ calls add_success
obsolete_assert_true_logical_ calls assert_true
assert_not_equals calls assert_not_equals_1d_real_, assert_not_equals_1d_logical_, assert_not_equals_2d_string_, assert_not_equals_1d_string_, assert_not_equals_complex_in_range_, assert_not_equals_2d_int_, assert_not_equals_1d_double_in_range_, assert_not_equals_2d_double_, assert_not_equals_2d_real_in_range_, assert_not_equals_2d_complex_, assert_not_equals_string_, assert_not_equals_int_, assert_not_equals_real_in_range_, assert_not_equals_2d_complex_in_range_, assert_not_equals_real_, assert_not_equals_1d_double_, assert_not_equals_complex_, assert_not_equals_1d_real_in_range_, assert_not_equals_2d_real_, assert_not_equals_double_, assert_not_equals_2d_double_in_range_, assert_not_equals_2d_logical_, assert_not_equals_double_in_range_, assert_not_equals_logical_, assert_not_equals_1d_int_, assert_not_equals_1d_complex_, assert_not_equals_1d_complex_in_range_
assert_false calls assert_false_
assertnotequals calls assert_not_equals_1d_real_, assert_not_equals_1d_logical_, assert_not_equals_2d_string_, assert_not_equals_1d_string_, assert_not_equals_complex_in_range_, assert_not_equals_2d_int_, assert_not_equals_1d_double_in_range_, assert_not_equals_2d_double_, assert_not_equals_2d_real_in_range_, assert_not_equals_2d_complex_, assert_not_equals_string_, assert_not_equals_int_, assert_not_equals_real_in_range_, assert_not_equals_2d_complex_in_range_, assert_not_equals_real_, assert_not_equals_1d_double_, assert_not_equals_complex_, assert_not_equals_1d_real_in_range_, assert_not_equals_2d_real_, assert_not_equals_double_, assert_not_equals_2d_double_in_range_, assert_not_equals_2d_logical_, assert_not_equals_double_in_range_, assert_not_equals_logical_, assert_not_equals_1d_int_, assert_not_equals_1d_complex_, assert_not_equals_1d_complex_in_range_
assert_equals calls assert_eq_2d_string_, assert_eq_real_in_range_, assert_eq_2d_logical_, assert_eq_2d_complex_in_range_, assert_eq_1d_string_, assert_eq_logical_, assert_eq_1d_int_, assert_eq_1d_logical_, assert_eq_1d_double_, assert_eq_1d_real_, assert_eq_double_in_range_, assert_eq_complex_, assert_eq_int_, assert_eq_2d_double_in_range_, assert_eq_1d_complex_in_range_, assert_eq_2d_real_in_range_, assert_eq_1d_double_in_range_, assert_eq_2d_int_, assert_eq_2d_complex_, assert_eq_string_, assert_eq_complex_in_range_, assert_eq_2d_real_, assert_eq_1d_complex_, assert_eq_2d_double_, assert_eq_double_, assert_eq_1d_real_in_range_, assert_eq_real_
addsuccess calls obsolete_addsuccess_
assertequals calls assert_eq_2d_string_, assert_eq_real_in_range_, assert_eq_2d_logical_, assert_eq_2d_complex_in_range_, assert_eq_1d_string_, assert_eq_logical_, assert_eq_1d_int_, assert_eq_1d_logical_, assert_eq_1d_double_, assert_eq_1d_real_, assert_eq_double_in_range_, assert_eq_complex_, assert_eq_int_, assert_eq_2d_double_in_range_, assert_eq_1d_complex_in_range_, assert_eq_2d_real_in_range_, assert_eq_1d_double_in_range_, assert_eq_2d_int_, assert_eq_2d_complex_, assert_eq_string_, assert_eq_complex_in_range_, assert_eq_2d_real_, assert_eq_1d_complex_, assert_eq_2d_double_, assert_eq_double_, assert_eq_1d_real_in_range_, assert_eq_real_
asserttrue calls obsolete_assert_true_logical_