add_fail_ – naturalFRUIT
add_fail_ Subroutine
4 statements
Source File
private subroutine add_fail_(message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
add_fail_
Source Code
  subroutine add_fail_ (message)
    character (*), intent (in), optional :: message
    call failed_assert_action('none', 'none', message, if_is = .true.)
  end subroutine add_fail_
Call graph
add_fail_ calls failed_assert_action
failed_assert_action calls increase_message_stack_, make_error_msg_, failed_mark_
make_error_msg_ calls strip
failed_mark_ calls output_mark_
strip calls strip_, strip_length_
add_fail_unit_ calls add_fail_
addfail calls add_fail_, add_fail_unit_
add_fail calls add_fail_, add_fail_unit_