assert_not_equals_2d_complex_in_range_ – naturalFRUIT
assert_not_equals_2d_complex_in_range_ Subroutine
21 statements
Source File
private subroutine assert_not_equals_2d_complex_in_range_(var1, var2, n, m, delta, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1(n,m)
complex(kind=kind(1.0D0)), intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_not_equals_2d_complex_in_range_
Source Code
  subroutine assert_not_equals_2d_complex_in_range_(var1, var2, n, m, delta, message)
    integer, intent (in) :: n, m
    integer              :: i, j
    complex(kind=kind(1.0D0)), intent (in) :: var1(n, m), var2(n, m)
    double precision, intent (in) :: delta
    character(len = *), intent (in), optional :: message
    logical :: same_so_far
    same_so_far = .true.
    do j = 1, m
      do i = 1, n
        if (abs(var1(i, j) - var2(i, j)) > delta) then
          same_so_far = .false.
        endif
      enddo
    enddo
    if (same_so_far) then
      call failed_assert_action(&
      & to_s(var1(1, 1)), &
      & to_s(var2(1, 1)), '2d array has no difference, ' // message, if_is = .false.)
      return
    endif
    call add_success
  end subroutine assert_not_equals_2d_complex_in_range_
Call graph
assert_not_equals_2d_complex_in_range_ calls add_success, to_s
add_success calls success_mark_
to_s calls to_s_int_, to_s_double_, to_s_complex_, to_s_double_complex_, to_s_logical_, to_s_real_, to_s_string_
success_mark_ calls output_mark_
assertnotequals calls assert_not_equals_2d_complex_in_range_
assert_not_equals calls assert_not_equals_2d_complex_in_range_