assert_eq_2d_logical_ – naturalFRUIT
assert_eq_2d_logical_ Subroutine
15 statements
Source File
private subroutine assert_eq_2d_logical_(var1, var2, n, m, message)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: var1(n,m)
logical, intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_eq_2d_logical_
Source Code
  subroutine assert_eq_2d_logical_(var1, var2, n, m, message)
    integer, intent (in) :: n, m
    integer              :: i, j
    logical, intent (in) :: var1(n, m), var2(n, m)
    character(len = *), intent (in), optional :: message
    do j = 1, m
      do i = 1, n
        if (var1(i, j) .neqv. var2(i, j)) then
          call failed_assert_action(&
          & to_s(var1(i, j)), &
          & to_s(var2(i, j)), '2d array has difference, ' // message, if_is = .true.)
          return
        endif
      enddo
    enddo
    call add_success
  end subroutine assert_eq_2d_logical_
Call graph
assert_eq_2d_logical_ calls to_s, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
add_success calls success_mark_
success_mark_ calls output_mark_
assert_equals calls assert_eq_2d_logical_
assertequals calls assert_eq_2d_logical_