assert_eq_complex_ – naturalFRUIT
assert_eq_complex_ Subroutine
9 statements
Source File
private subroutine assert_eq_complex_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1
complex(kind=kind(1.0D0)), intent(in) :: var2
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_eq_complex_
Source Code
  subroutine assert_eq_complex_(var1, var2, message)
    complex(kind=kind(1.0D0)), intent (in) :: var1, var2
    character(len = *), intent (in), optional :: message
        if ((real (var1) < real (var2)) .or. &
&(real (var1) > real (var2)) .or. &
&(aimag(var1) < aimag(var2)) .or. &
&(aimag(var1) > aimag(var2))) then
          call failed_assert_action(&
          & to_s(var1), &
          & to_s(var2), message, if_is = .true.)
          return
        endif
    call add_success
  end subroutine assert_eq_complex_
Call graph
assert_eq_complex_ calls add_success, to_s
add_success calls success_mark_
to_s calls to_s_int_, to_s_double_, to_s_complex_, to_s_double_complex_, to_s_logical_, to_s_real_, to_s_string_
success_mark_ calls output_mark_
assert_equals calls assert_eq_complex_
assertequals calls assert_eq_complex_