assert_not_equals_1d_int_ – naturalFRUIT
assert_not_equals_1d_int_ Subroutine
18 statements
Source File
private subroutine assert_not_equals_1d_int_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: var1(n)
integer, intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_not_equals_1d_int_
Source Code
  subroutine assert_not_equals_1d_int_(var1, var2, n, message)
    integer, intent (in) :: n
    integer              :: i
    integer, intent (in) :: var1(n), var2(n)
    character(len = *), intent (in), optional :: message
    logical :: same_so_far
    same_so_far = .true.
    do i = 1, n
        if (var1(i) /= var2(i)) then
          same_so_far = .false.
        endif
    enddo
    if (same_so_far) then
      call failed_assert_action(&
      & to_s(var1(1)), &
      & to_s(var2(1)), '1d array has no difference, ' // message, if_is = .false.)
      return
    endif
    call add_success
  end subroutine assert_not_equals_1d_int_
Call graph
assert_not_equals_1d_int_ calls to_s, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
add_success calls success_mark_
success_mark_ calls output_mark_
assert_not_equals calls assert_not_equals_1d_int_
assertnotequals calls assert_not_equals_1d_int_