assert_not_equals_string_ – naturalFRUIT
assert_not_equals_string_ Subroutine
14 statements
Source File
private subroutine assert_not_equals_string_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var1
character(len=*), intent(in) :: var2
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_not_equals_string_
Source Code
  subroutine assert_not_equals_string_(var1, var2, message)
    character (len = *), intent (in) :: var1, var2
    character(len = *), intent (in), optional :: message
    logical :: same_so_far
    same_so_far = .true.
        if (trim(strip(var1)) /= trim(strip(var2))) then
          same_so_far = .false.
        endif
    if (same_so_far) then
      call failed_assert_action(&
      & to_s(var1), &
      & to_s(var2), message, if_is = .false.)
      return
    endif
    call add_success
  end subroutine assert_not_equals_string_
Call graph
assert_not_equals_string_ calls add_success, strip, to_s
add_success calls success_mark_
strip calls strip_length_, strip_
to_s calls to_s_int_, to_s_double_, to_s_complex_, to_s_double_complex_, to_s_logical_, to_s_real_, to_s_string_
success_mark_ calls output_mark_
assertnotequals calls assert_not_equals_string_
assert_not_equals calls assert_not_equals_string_