assert_true – naturalFRUIT
assert_true Subroutine
9 statements
Source File
public subroutine assert_true(var1, message)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: var1
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_true
Source Code
  subroutine assert_true (var1, message)
    logical, intent (in) :: var1
    character (*), intent (in), optional :: message
    if ( var1 .eqv. .true.) then
       call add_success
    else
       call failed_assert_action(to_s(.true.), to_s(var1), message, if_is = .true.)
    end if
  end subroutine assert_true
Call graph
assert_true calls to_s, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
add_success calls success_mark_
success_mark_ calls output_mark_
obsolete_assert_true_logical_ calls assert_true
asserttrue calls obsolete_assert_true_logical_