assert_eq_string_ – naturalFRUIT
assert_eq_string_ Subroutine
9 statements
Source File
private subroutine assert_eq_string_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var1
character(len=*), intent(in) :: var2
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_eq_string_
Source Code
  subroutine assert_eq_string_(var1, var2, message)
    character (len = *), intent (in) :: var1, var2
    character(len = *), intent (in), optional :: message
        if (trim(strip(var1)) /= trim(strip(var2))) then
          call failed_assert_action(&
          & to_s(var1), &
          & to_s(var2), message, if_is = .true.)
          return
        endif
    call add_success
  end subroutine assert_eq_string_
Call graph
assert_eq_string_ calls to_s, strip, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
strip calls strip_, strip_length_
add_success calls success_mark_
success_mark_ calls output_mark_
assert_equals calls assert_eq_string_
assertequals calls assert_eq_string_