assert_false_ – naturalFRUIT
assert_false_ Subroutine
9 statements
Source File
private subroutine assert_false_(var1, message)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: var1
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_false_
Source Code
  subroutine assert_false_(var1, message)
    logical, intent(in) :: var1
    character(len = *), intent(in), optional :: message
    if (var1 .eqv. .false.) then
      call add_success
    else
      call failed_assert_action(to_s(.true.), to_s(var1), message, if_is = .false.)
    endif
  end subroutine assert_false_
Call graph
assert_false_ calls add_success, to_s
add_success calls success_mark_
to_s calls to_s_int_, to_s_double_, to_s_complex_, to_s_double_complex_, to_s_logical_, to_s_real_, to_s_string_
success_mark_ calls output_mark_
assert_false calls assert_false_