assert_eq_1d_string_ – naturalFRUIT
assert_eq_1d_string_ Subroutine
13 statements
Source File
private subroutine assert_eq_1d_string_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var1(n)
character(len=*), intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_eq_1d_string_
Source Code
  subroutine assert_eq_1d_string_(var1, var2, n, message)
    integer, intent (in) :: n
    integer              :: i
    character (len = *), intent (in) :: var1(n), var2(n)
    character(len = *), intent (in), optional :: message
    do i = 1, n
        if (trim(strip(var1(i))) /= trim(strip(var2(i)))) then
          call failed_assert_action(&
          & to_s(var1(i)), &
          & to_s(var2(i)), '1d array has difference, ' // message, if_is = .true.)
          return
        endif
    enddo
    call add_success
  end subroutine assert_eq_1d_string_
Call graph
assert_eq_1d_string_ calls to_s, strip, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
strip calls strip_, strip_length_
add_success calls success_mark_
success_mark_ calls output_mark_
assert_equals calls assert_eq_1d_string_
assertequals calls assert_eq_1d_string_