assert_eq_2d_complex_in_range_ – naturalFRUIT
assert_eq_2d_complex_in_range_ Subroutine
16 statements
Source File
private subroutine assert_eq_2d_complex_in_range_(var1, var2, n, m, delta, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1(n,m)
complex(kind=kind(1.0D0)), intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_eq_2d_complex_in_range_
Source Code
  subroutine assert_eq_2d_complex_in_range_(var1, var2, n, m, delta, message)
    integer, intent (in) :: n, m
    integer              :: i, j
    complex(kind=kind(1.0D0)), intent (in) :: var1(n, m), var2(n, m)
    double precision, intent (in) :: delta
    character(len = *), intent (in), optional :: message
    do j = 1, m
      do i = 1, n
        if (abs(var1(i, j) - var2(i, j)) > delta) then
          call failed_assert_action(&
          & to_s(var1(i, j)), &
          & to_s(var2(i, j)), '2d array has difference, ' // message, if_is = .true.)
          return
        endif
      enddo
    enddo
    call add_success
  end subroutine assert_eq_2d_complex_in_range_
Call graph
assert_eq_2d_complex_in_range_ calls add_success, to_s
add_success calls success_mark_
to_s calls to_s_int_, to_s_double_, to_s_complex_, to_s_double_complex_, to_s_logical_, to_s_real_, to_s_string_
success_mark_ calls output_mark_
assert_equals calls assert_eq_2d_complex_in_range_
assertequals calls assert_eq_2d_complex_in_range_