assert_not_equals_complex_in_range_ – naturalFRUIT
assert_not_equals_complex_in_range_ Subroutine
15 statements
Source File
private subroutine assert_not_equals_complex_in_range_(var1, var2, delta, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1
complex(kind=kind(1.0D0)), intent(in) :: var2
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_not_equals_complex_in_range_
Source Code
  subroutine assert_not_equals_complex_in_range_(var1, var2, delta, message)
    complex(kind=kind(1.0D0)), intent (in) :: var1, var2
    double precision, intent (in) :: delta
    character(len = *), intent (in), optional :: message
    logical :: same_so_far
    same_so_far = .true.
        if (abs(var1 - var2) > delta) then
          same_so_far = .false.
        endif
    if (same_so_far) then
      call failed_assert_action(&
      & to_s(var1), &
      & to_s(var2), message, if_is = .false.)
      return
    endif
    call add_success
  end subroutine assert_not_equals_complex_in_range_
Call graph
assert_not_equals_complex_in_range_ calls to_s, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
add_success calls success_mark_
success_mark_ calls output_mark_
assert_not_equals calls assert_not_equals_complex_in_range_
assertnotequals calls assert_not_equals_complex_in_range_