assert_eq_real_in_range_ – naturalFRUIT
assert_eq_real_in_range_ Subroutine
10 statements
Source File
private subroutine assert_eq_real_in_range_(var1, var2, delta, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1
real, intent(in) :: var2
real, intent(in) :: delta
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_eq_real_in_range_
Source Code
  subroutine assert_eq_real_in_range_(var1, var2, delta, message)
    real, intent (in) :: var1, var2
    real, intent (in) :: delta
    character(len = *), intent (in), optional :: message
        if (abs(var1 - var2) > delta) then
          call failed_assert_action(&
          & to_s(var1), &
          & to_s(var2), message, if_is = .true.)
          return
        endif
    call add_success
  end subroutine assert_eq_real_in_range_
Call graph
assert_eq_real_in_range_ calls to_s, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
add_success calls success_mark_
success_mark_ calls output_mark_
assert_equals calls assert_eq_real_in_range_
assertequals calls assert_eq_real_in_range_