assert_not_equals_real_ – naturalFRUIT
assert_not_equals_real_ Subroutine
14 statements
Source File
private subroutine assert_not_equals_real_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1
real, intent(in) :: var2
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
assert_not_equals_real_
Source Code
  subroutine assert_not_equals_real_(var1, var2, message)
    real, intent (in) :: var1, var2
    character(len = *), intent (in), optional :: message
    logical :: same_so_far
    same_so_far = .true.
        if ((var1 < var2) .or. (var1 > var2)) then
          same_so_far = .false.
        endif
    if (same_so_far) then
      call failed_assert_action(&
      & to_s(var1), &
      & to_s(var2), message, if_is = .false.)
      return
    endif
    call add_success
  end subroutine assert_not_equals_real_
Call graph
assert_not_equals_real_ calls add_success, to_s
add_success calls success_mark_
to_s calls to_s_int_, to_s_double_, to_s_complex_, to_s_double_complex_, to_s_logical_, to_s_real_, to_s_string_
success_mark_ calls output_mark_
assertnotequals calls assert_not_equals_real_
assert_not_equals calls assert_not_equals_real_