case_failed_xml_ – naturalFRUIT
case_failed_xml_ Subroutine
26 statements
Source File
private subroutine case_failed_xml_(tc_name, classname)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: tc_name
character(len=*), intent(in) :: classname
Calls
Called by
Contents
Source Code
case_failed_xml_
Source Code
  subroutine case_failed_xml_(tc_name, classname)
    character(*), intent(in) :: tc_name
    character(*), intent(in) :: classname
    integer :: i, j
    character(len = STRLEN_T) :: case_time
    case_time = case_delta_t()
    open (xml_work, FILE = xml_filename_work, position='append')
    write(xml_work, &
   &  '("    <testcase name=""", a, """ classname=""", a, a, """ time=""", a, """>")') &
   &  trim(tc_name), trim(prefix), trim(classname), trim(case_time)
    write(xml_work, '("      <failure type=""failure"" message=""")', advance = "no")
    do i = message_index_from, message_index - 1
      j = i - message_index_from + 1
      if (j > MAX_NUM_FAILURES_IN_XML) then
        write(xml_work, '("(omit the rest)")', advance="no")
        exit
      endif
      write(xml_work, '(a)', advance = "no") trim(strip(message_array(i)))
      if (i == message_index - 1) then
        continue
      else
        write(xml_work, '("&#xA;")', advance="no")
      endif
    enddo
    write(xml_work, '("""/>")')
    write(xml_work, &
   &  '("    </testcase>")')
    close(xml_work)
  end subroutine case_failed_xml_
Call graph
case_failed_xml_ calls case_delta_t, strip
strip calls strip_, strip_length_
case_failed_xml calls case_failed_xml_