failed_assert_action – naturalFRUIT
failed_assert_action Subroutine
15 statements
Source File
public subroutine failed_assert_action(expected, got, message, if_is)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: expected
character(len=*), intent(in) :: got
character(len=*), intent(in), optional :: message
logical, intent(in), optional :: if_is
Calls
Called by
Contents
Source Code
failed_assert_action
Source Code
  subroutine failed_assert_action (expected, got, message, if_is)
    character(*), intent(in) :: expected, got
    character(*), intent(in), optional :: message
    logical, intent(in), optional :: if_is
    !$omp critical     (FRUIT_OMP_ADD_FAIL)
    if (present(if_is)) then
      call make_error_msg_ (expected, got, if_is,  message)
    else
      call make_error_msg_ (expected, got, .true., message)
    endif
    call increase_message_stack_
    failed_assert_count = failed_assert_count + 1
    last_passed = .false.
    case_passed = .false.
    !$omp end critical (FRUIT_OMP_ADD_FAIL)
    call failed_mark_
  end subroutine failed_assert_action
Call graph
failed_assert_action calls increase_message_stack_, make_error_msg_, failed_mark_
make_error_msg_ calls strip
failed_mark_ calls output_mark_
strip calls strip_, strip_length_
add_fail_ calls failed_assert_action
add_fail_unit_ calls add_fail_
addfail calls add_fail_, add_fail_unit_
add_fail calls add_fail_, add_fail_unit_