fruit_summary_mpi_xml_ – naturalFRUIT
fruit_summary_mpi_xml_ Subroutine
54 statements
Source File
private subroutine fruit_summary_mpi_xml_(size, rank)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: size
integer, intent(in) :: rank
Calls
Called by
Contents
Source Code
fruit_summary_mpi_xml_
Source Code
  subroutine     fruit_summary_mpi_xml_(size, rank)
    integer, intent(in) :: size, rank
    character(len = 1000) :: whole_line
    character(len =  100) :: full_count
    character(len =  100) :: fail_count
    character(len = FN_LENGTH)              :: xml_filename_work
    character(len = FN_LENGTH), allocatable :: xml_filename_work_all(:)
    integer :: fail_assert    , succ_assert    , fail_case     , succ_case
    integer :: fail_assert_sum, succ_assert_sum, fail_case_sum , succ_case_sum
    integer :: i
    integer :: status(MPI_STATUS_SIZE)
    integer :: ierr
    call get_xml_filename_work(xml_filename_work)
    allocate(xml_filename_work_all(size))
    if (rank /= 0) then
    call MPI_Send(    xml_filename_work, &
    &     FN_LENGTH, MPI_CHARACTER,     0, 8, MPI_COMM_WORLD, ierr)
    endif
    if (rank == 0) then
      xml_filename_work_all(1) = xml_filename_work
      do i = 1+1, size
        call MPI_RECV(xml_filename_work_all(i), &
        & FN_LENGTH, MPI_CHARACTER, i - 1, 8, MPI_COMM_WORLD, status, ierr)
      enddo
    endif
    call get_assert_and_case_count(&
    & fail_assert,  succ_assert, &
    & fail_case,    succ_case)
    call MPI_REDUCE(&
    & fail_assert    , &
    & fail_assert_sum, 1, MPI_INTEGER, MPI_SUM, 0, MPI_COMM_WORLD, ierr)
    call MPI_REDUCE(&
    & succ_assert    , &
    & succ_assert_sum, 1, MPI_INTEGER, MPI_SUM, 0, MPI_COMM_WORLD, ierr)
    call MPI_REDUCE(&
    & fail_case    , &
    & fail_case_sum,   1, MPI_INTEGER, MPI_SUM, 0, MPI_COMM_WORLD, ierr)
    call MPI_REDUCE(&
    & succ_case    , &
    & succ_case_sum,   1, MPI_INTEGER, MPI_SUM, 0, MPI_COMM_WORLD, ierr)
    full_count = int_to_str(succ_case_sum + fail_case_sum)
    fail_count = int_to_str(                fail_case_sum)
    if (rank == 0) then
      open (XML_OPEN, file = xml_filename, action ="write", status = "replace")
        write(XML_OPEN, '("<?xml version=""1.0"" encoding=""UTF-8""?>")')
        write(XML_OPEN, '("<testsuites>")')
        write(XML_OPEN, '("  <testsuite errors=""0"" ")', advance = "no")
        write(XML_OPEN, '("tests=""", a, """ ")', advance = "no") &
        &  trim(full_count)
        write(XML_OPEN, '("failures=""", a, """ ")', advance = "no") &
        &  trim(fail_count)
        write(XML_OPEN, '("name=""", a, """ ")', advance = "no") &
        &  "name of test suite"
        write(XML_OPEN, '("id=""1"">")')
        do i = 1, size
          open (XML_WORK, FILE = xml_filename_work_all(i))
            do
              read(XML_WORK, '(a)', end = 999) whole_line
              write(XML_OPEN, '(a)') trim(whole_line)
            enddo
        999 continue
          close(XML_WORK)
        enddo
        write(XML_OPEN, '("  </testsuite>")')
        write(XML_OPEN, '("</testsuites>")')
      close(XML_OPEN)
    endif
    if (size < 0) print *, "size < 0"
  end subroutine fruit_summary_mpi_xml_
Call graph
fruit_summary_mpi_xml_ calls int_to_str, get_assert_and_case_count, mpi_reduce, get_xml_filename_work, mpi_send
get_assert_and_case_count calls get_assert_and_case_count_
get_xml_filename_work calls get_xml_filename_work_
fruit_summary_mpi_xml calls fruit_summary_mpi_xml_