fruit_finalize_mpi_ – naturalFRUIT
fruit_finalize_mpi_ Subroutine
6 statements
Source File
private subroutine fruit_finalize_mpi_(size, rank)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: size
integer, intent(in) :: rank
Calls
Called by
Contents
Source Code
fruit_finalize_mpi_
Source Code
  subroutine     fruit_finalize_mpi_(size, rank)
    integer, intent(in) :: size, rank
    if (size < 0) print *, "size negative"
    if (rank < 0) print *, "rank negative"
    call         fruit_finalize
  end subroutine fruit_finalize_mpi_
Call graph
fruit_finalize_mpi_ calls fruit_finalize
fruit_finalize calls fruit_finalize_
fruit_finalize_mpi calls fruit_finalize_mpi_