fruit_init_mpi_xml_ – naturalFRUIT
fruit_init_mpi_xml_ Subroutine
7 statements
Source File
private subroutine fruit_init_mpi_xml_(rank)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: rank
Calls
Called by
Contents
Source Code
fruit_init_mpi_xml_
Source Code
  subroutine fruit_init_mpi_xml_(rank)
    integer, intent(in) :: rank
    character(len = FN_LENGTH) :: xml_filename_work
    write(xml_filename_work, '("result_tmp_", i5.5, ".xml")') rank
    call set_xml_filename_work(xml_filename_work)
    call init_fruit_xml(rank)
  end subroutine fruit_init_mpi_xml_
Call graph
fruit_init_mpi_xml_ calls init_fruit_xml, set_xml_filename_work
init_fruit_xml calls init_fruit_xml_
set_xml_filename_work calls set_xml_filename_work_
fruit_init_mpi_xml calls fruit_init_mpi_xml_