increase_message_stack_ – naturalFRUIT
increase_message_stack_ Subroutine
22 statements
Source File
private subroutine increase_message_stack_()
Arguments
None
Called by
Contents
Source Code
increase_message_stack_
Source Code
  subroutine increase_message_stack_
    character(len=MSG_LENGTH) :: msg_swap_holder(current_max)
    if (message_index > MAX_MSG_STACK_SIZE) then
      return
    end if
    if (message_index > current_max) then
      msg_swap_holder(1:current_max) = message_array(1:current_max)
      deallocate(message_array)
      current_max = current_max + MSG_ARRAY_INCREMENT
      allocate(message_array(current_max))
      message_array(1:current_max - MSG_ARRAY_INCREMENT) &
                   = msg_swap_holder(1: current_max - MSG_ARRAY_INCREMENT)
    end if
    message_array (message_index) = msg
    if (message_index == MAX_MSG_STACK_SIZE) then
      message_array(message_index) = "Max number of messages reached. Further messages suppressed."
    endif
    message_index = message_index + 1
    if (message_index > MAX_MSG_STACK_SIZE) then
       write(stdout,*) "Stop because there are too many error messages to put into stack."
       write(stdout,*) "Try to increase MAX_MSG_STACK_SIZE if you really need so."
    end if
  end subroutine increase_message_stack_
Call graph
failed_assert_action calls increase_message_stack_
add_fail_ calls failed_assert_action
add_fail_unit_ calls add_fail_
addfail calls add_fail_, add_fail_unit_
add_fail calls add_fail_, add_fail_unit_