init_fruit_xml_ – naturalFRUIT
init_fruit_xml_ Subroutine
31 statements
Source File
private subroutine init_fruit_xml_(rank)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: rank
Called by
Contents
Source Code
init_fruit_xml_
Source Code
  subroutine init_fruit_xml_(rank)
    integer, optional, intent(in) :: rank
    logical :: rank_zero_or_single
    rank_zero_or_single = .true.
    if (present(rank)) then
      if (rank /= 0) then
        rank_zero_or_single = .false.
      endif
    endif
    if (rank_zero_or_single) then
      open (XML_OPEN, file = xml_filename, action ="write", status = "replace")
        write(XML_OPEN, '("<?xml version=""1.0"" encoding=""UTF-8""?>")')
        write(XML_OPEN, '("<testsuites>")')
        write(XML_OPEN, '("  <testsuite ")', advance = "no")
        write(XML_OPEN, '(      "errors=""0"" "   )', advance = "no")
        write(XML_OPEN, '(      "tests=""1"" "    )', advance = "no")
        write(XML_OPEN, '(      "failures=""1"" " )', advance = "no")
        write(XML_OPEN, '(      "name=""", a, """ ")', advance = "no") "name of test suite"
        write(XML_OPEN, '(      "id=""1"">")')
        write(XML_OPEN, &
        &  '("    <testcase name=""", a, """ classname=""", a, """ time=""", a, """>")') &
        &  "dummy_testcase", "dummy_classname", "0"
        write(XML_OPEN, '(a)', advance = "no") "      <failure type=""failure"" message="""
        write(XML_OPEN, '(a)', advance = "no") "FRUIT did not generate regular content of result.xml."
        write(XML_OPEN, '(a)')                 """/>"
        write(XML_OPEN, '("    </testcase>")')
        write(XML_OPEN, '("  </testsuite>")')
        write(XML_OPEN, '("</testsuites>")')
      close(XML_OPEN)
    endif
    open (xml_work, FILE = xml_filename_work, action ="write", status='replace')
    close(xml_work)
  end subroutine init_fruit_xml_
Call graph
init_fruit_xml calls init_fruit_xml_
fruit_init_mpi_xml_ calls init_fruit_xml
fruit_init_mpi_xml calls fruit_init_mpi_xml_