make_error_msg_ – naturalFRUIT
make_error_msg_ Subroutine
17 statements
Source File
private subroutine make_error_msg_(var1, var2, if_is, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var1
character(len=*), intent(in) :: var2
logical, intent(in) :: if_is
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
make_error_msg_
Source Code
  subroutine make_error_msg_ (var1, var2, if_is, message)
    character(*), intent(in) :: var1, var2
    logical,      intent(in)           :: if_is
    character(*), intent(in), optional :: message
    msg = '[' // trim(strip(case_name)) // ']: '
    if (if_is) then
      msg = trim(msg) //     'Expected'
    else
      msg = trim(msg) // 'Expected Not'
    endif
    msg = trim(msg) // " " // '[' // trim(strip(var1)) // '], '
    msg = trim(msg) // " " // 'Got'
    msg = trim(msg) // " " // '[' // trim(strip(var2)) // ']'
    if (present(message)) then
       msg = trim(msg) // '; User message: [' // trim(message) // ']'
    endif
  end subroutine make_error_msg_
Call graph
make_error_msg_ calls strip
strip calls strip_, strip_length_
failed_assert_action calls make_error_msg_
add_fail_ calls failed_assert_action
add_fail_unit_ calls add_fail_
addfail calls add_fail_, add_fail_unit_
add_fail calls add_fail_, add_fail_unit_