obsolete_getTestSummary_ – naturalFRUIT
obsolete_getTestSummary_ Subroutine
4 statements
Source File
private subroutine obsolete_getTestSummary_()
Arguments
None
Calls
Called by
Contents
Source Code
obsolete_getTestSummary_
Source Code
  subroutine obsolete_getTestSummary_
    call obsolete_ ( "getTestSummary is OBSOLETE.  replaced by fruit_summary")
    call fruit_summary_
  end subroutine obsolete_getTestSummary_
Call graph
obsolete_gettestsummary_ calls fruit_summary_, obsolete_
fruit_summary_ calls strip, fruit_summary_table_
strip calls strip_, strip_length_
gettestsummary calls obsolete_gettestsummary_