obsolete_getTotalCount_ – naturalFRUIT
obsolete_getTotalCount_ Subroutine
5 statements
Source File
private subroutine obsolete_getTotalCount_(count)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: count
Calls
Called by
Contents
Source Code
obsolete_getTotalCount_
Source Code
  subroutine obsolete_getTotalCount_ (count)
    integer, intent (out) :: count
    call obsolete_ (' getTotalCount subroutine is replaced by function get_total_count')
    call get_total_count(count)
  end subroutine obsolete_getTotalCount_
Call graph
obsolete_gettotalcount_ calls obsolete_, get_total_count
gettotalcount calls obsolete_gettotalcount_