obsolete_ – naturalFRUIT
obsolete_ Subroutine
13 statements
Source File
private subroutine obsolete_(message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: message
Called by
Contents
Source Code
obsolete_
Source Code
  subroutine obsolete_ (message)
    character (*), intent (in), optional :: message
    write (stdout,*)
    write (stdout,*) "<<<<<<<<<<<<<<<<<<<<<<<<<< WARNING from FRUIT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    write (stdout,*) message
    write (stdout,*)
    write (stdout,*) " old calls will be replaced in the next release in Jan 2009"
    write (stdout,*) " Naming convention for all the method calls are changed to: first_name from"
    write (stdout,*) " firstName.  Subroutines that will be deleted: assertEquals, assertNotEquals,"
    write (stdout,*) " assertTrue, addSuccessful, addFail, etc."
    write (stdout,*) "<<<<<<<<<<<<<<<<<<<<<<<<<< WARNING from FRUIT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    write (stdout,*)
  end subroutine obsolete_
Call graph
obsolete_gettotalcount_ calls obsolete_
obsolete_addsuccess_ calls obsolete_
obsolete_gettestsummary_ calls obsolete_
obsolete_getfailedcount_ calls obsolete_
obsolete_assert_true_logical_ calls obsolete_
obsolete_isallsuccessful_ calls obsolete_
obsolete_initializefruit_ calls obsolete_
gettestsummary calls obsolete_gettestsummary_
initializefruit calls obsolete_initializefruit_
addsuccess calls obsolete_addsuccess_
asserttrue calls obsolete_assert_true_logical_
getfailedcount calls obsolete_getfailedcount_
isallsuccessful calls obsolete_isallsuccessful_
gettotalcount calls obsolete_gettotalcount_