obsolete_assert_true_logical_ – naturalFRUIT
obsolete_assert_true_logical_ Subroutine
6 statements
Source File
private subroutine obsolete_assert_true_logical_(var1, message)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: var1
character(len=*), intent(in), optional :: message
Calls
Called by
Contents
Source Code
obsolete_assert_true_logical_
Source Code
  subroutine obsolete_assert_true_logical_(var1, message)
    logical, intent (in) :: var1
    character (*), intent (in), optional :: message
    call obsolete_ ('assertTrue subroutine is replaced by function assert_true')
    call assert_true(var1, message)
  end subroutine obsolete_assert_true_logical_
Call graph
obsolete_assert_true_logical_ calls obsolete_, assert_true
assert_true calls add_success, to_s
add_success calls success_mark_
to_s calls to_s_int_, to_s_double_, to_s_complex_, to_s_double_complex_, to_s_logical_, to_s_real_, to_s_string_
success_mark_ calls output_mark_
asserttrue calls obsolete_assert_true_logical_