obsolete_addSuccess_ – naturalFRUIT
obsolete_addSuccess_ Subroutine
4 statements
Source File
private subroutine obsolete_addSuccess_()
Arguments
None
Calls
Called by
Contents
Source Code
obsolete_addSuccess_
Source Code
  subroutine obsolete_addSuccess_
    call obsolete_ ("addSuccess is OBSOLETE.  replaced by add_success")
    call add_success
  end subroutine obsolete_addSuccess_
Call graph
obsolete_addsuccess_ calls obsolete_, add_success
add_success calls success_mark_
success_mark_ calls output_mark_
addsuccess calls obsolete_addsuccess_