obsolete_initializeFruit_ – naturalFRUIT
obsolete_initializeFruit_ Subroutine
4 statements
Source File
private subroutine obsolete_initializeFruit_()
Arguments
None
Calls
Called by
Contents
Source Code
obsolete_initializeFruit_
Source Code
  subroutine obsolete_initializeFruit_
    call obsolete_ ("initializeFruit is OBSOLETE.  replaced by init_fruit")
    call init_fruit
  end subroutine obsolete_initializeFruit_
Call graph
obsolete_initializefruit_ calls obsolete_, init_fruit
initializefruit calls obsolete_initializefruit_