output_mark_ – naturalFRUIT
output_mark_ Subroutine
10 statements
Source File
private subroutine output_mark_(chr)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: chr
integer, save :: linechar_count = 0 Definition of linechar_count is moved to module, so that it can be stashed and restored.
Called by
Contents
Source Code
output_mark_
Source Code
  subroutine output_mark_( chr )
    character(1), intent(in) :: chr
  !!  integer, save :: linechar_count = 0
  !!  Definition of linechar_count is moved to module,
  !!  so that it can be stashed and restored.
    !$omp critical      (FRUIT_OMP_ADD_OUTPUT_MARK)
    linechar_count = linechar_count + 1
    if ( linechar_count .lt. MAX_MARKS_PER_LINE ) then
       write(stdout,"(A1)",ADVANCE='NO') chr
    else
       write(stdout,"(A1)",ADVANCE='YES') chr
       linechar_count = 0
    endif
    !$omp end critical  (FRUIT_OMP_ADD_OUTPUT_MARK)
  end subroutine output_mark_
Call graph
failed_mark_ calls output_mark_
success_mark_ calls output_mark_
failed_assert_action calls failed_mark_
add_success calls success_mark_
assert_not_equals_double_ calls add_success
assert_eq_2d_double_ calls add_success
obsolete_addsuccess_ calls add_success
assert_eq_logical_ calls add_success
assert_false_ calls add_success
assert_not_equals_2d_complex_ calls add_success
assert_eq_1d_real_ calls add_success
assert_eq_1d_logical_ calls add_success
assert_eq_2d_string_ calls add_success
assert_eq_2d_int_ calls add_success
assert_eq_1d_double_ calls add_success
assert_eq_complex_ calls add_success
assert_eq_1d_double_in_range_ calls add_success
assert_eq_2d_complex_ calls add_success
assert_eq_1d_real_in_range_ calls add_success
assert_not_equals_1d_real_ calls add_success
assert_not_equals_2d_logical_ calls add_success
assert_not_equals_logical_ calls add_success
assert_not_equals_1d_logical_ calls add_success
assert_eq_1d_string_ calls add_success
assert_eq_complex_in_range_ calls add_success
assert_not_equals_real_ calls add_success
assert_eq_double_ calls add_success
assert_not_equals_2d_real_in_range_ calls add_success
assert_eq_string_ calls add_success
assert_not_equals_complex_in_range_ calls add_success
assert_not_equals_2d_string_ calls add_success
assert_not_equals_complex_ calls add_success
assert_not_equals_2d_int_ calls add_success
assert_not_equals_2d_complex_in_range_ calls add_success
assert_eq_real_in_range_ calls add_success
assert_eq_2d_logical_ calls add_success
assert_not_equals_1d_double_ calls add_success
assert_not_equals_1d_string_ calls add_success
assert_eq_int_ calls add_success
assert_eq_2d_complex_in_range_ calls add_success
assert_not_equals_1d_complex_ calls add_success
assert_not_equals_1d_complex_in_range_ calls add_success
assert_not_equals_int_ calls add_success
assert_eq_1d_complex_ calls add_success
assert_eq_1d_int_ calls add_success
add_fail_ calls failed_assert_action
assert_not_equals_string_ calls add_success
assert_not_equals_2d_real_ calls add_success
assert_not_equals_1d_real_in_range_ calls add_success
assert_not_equals_2d_double_in_range_ calls add_success
assert_eq_1d_complex_in_range_ calls add_success
assert_not_equals_1d_int_ calls add_success
assert_eq_real_ calls add_success
assert_not_equals_1d_double_in_range_ calls add_success
assert_not_equals_2d_double_ calls add_success
assert_eq_2d_real_in_range_ calls add_success
assert_eq_2d_real_ calls add_success
assert_true calls add_success
assert_not_equals_real_in_range_ calls add_success
assert_eq_double_in_range_ calls add_success
assert_not_equals_double_in_range_ calls add_success
assert_eq_2d_double_in_range_ calls add_success
add_fail_unit_ calls add_fail_
assert_equals calls assert_eq_2d_double_, assert_eq_logical_, assert_eq_1d_real_, assert_eq_1d_logical_, assert_eq_2d_string_, assert_eq_2d_int_, assert_eq_1d_double_, assert_eq_complex_, assert_eq_1d_double_in_range_, assert_eq_2d_complex_, assert_eq_1d_real_in_range_, assert_eq_1d_string_, assert_eq_complex_in_range_, assert_eq_double_, assert_eq_string_, assert_eq_real_in_range_, assert_eq_2d_logical_, assert_eq_int_, assert_eq_2d_complex_in_range_, assert_eq_1d_complex_, assert_eq_1d_int_, assert_eq_1d_complex_in_range_, assert_eq_real_, assert_eq_2d_real_in_range_, assert_eq_2d_real_, assert_eq_double_in_range_, assert_eq_2d_double_in_range_
assertequals calls assert_eq_2d_double_, assert_eq_logical_, assert_eq_1d_real_, assert_eq_1d_logical_, assert_eq_2d_string_, assert_eq_2d_int_, assert_eq_1d_double_, assert_eq_complex_, assert_eq_1d_double_in_range_, assert_eq_2d_complex_, assert_eq_1d_real_in_range_, assert_eq_1d_string_, assert_eq_complex_in_range_, assert_eq_double_, assert_eq_string_, assert_eq_real_in_range_, assert_eq_2d_logical_, assert_eq_int_, assert_eq_2d_complex_in_range_, assert_eq_1d_complex_, assert_eq_1d_int_, assert_eq_1d_complex_in_range_, assert_eq_real_, assert_eq_2d_real_in_range_, assert_eq_2d_real_, assert_eq_double_in_range_, assert_eq_2d_double_in_range_
addfail calls add_fail_, add_fail_unit_
addsuccess calls obsolete_addsuccess_
add_fail calls add_fail_, add_fail_unit_
obsolete_assert_true_logical_ calls assert_true
assert_not_equals calls assert_not_equals_double_, assert_not_equals_2d_complex_, assert_not_equals_1d_real_, assert_not_equals_2d_logical_, assert_not_equals_logical_, assert_not_equals_1d_logical_, assert_not_equals_real_, assert_not_equals_2d_real_in_range_, assert_not_equals_complex_in_range_, assert_not_equals_2d_string_, assert_not_equals_complex_, assert_not_equals_2d_int_, assert_not_equals_2d_complex_in_range_, assert_not_equals_1d_double_, assert_not_equals_1d_string_, assert_not_equals_1d_complex_, assert_not_equals_1d_complex_in_range_, assert_not_equals_int_, assert_not_equals_string_, assert_not_equals_2d_real_, assert_not_equals_1d_real_in_range_, assert_not_equals_2d_double_in_range_, assert_not_equals_1d_int_, assert_not_equals_1d_double_in_range_, assert_not_equals_2d_double_, assert_not_equals_real_in_range_, assert_not_equals_double_in_range_
assertnotequals calls assert_not_equals_double_, assert_not_equals_2d_complex_, assert_not_equals_1d_real_, assert_not_equals_2d_logical_, assert_not_equals_logical_, assert_not_equals_1d_logical_, assert_not_equals_real_, assert_not_equals_2d_real_in_range_, assert_not_equals_complex_in_range_, assert_not_equals_2d_string_, assert_not_equals_complex_, assert_not_equals_2d_int_, assert_not_equals_2d_complex_in_range_, assert_not_equals_1d_double_, assert_not_equals_1d_string_, assert_not_equals_1d_complex_, assert_not_equals_1d_complex_in_range_, assert_not_equals_int_, assert_not_equals_string_, assert_not_equals_2d_real_, assert_not_equals_1d_real_in_range_, assert_not_equals_2d_double_in_range_, assert_not_equals_1d_int_, assert_not_equals_1d_double_in_range_, assert_not_equals_2d_double_, assert_not_equals_real_in_range_, assert_not_equals_double_in_range_
assert_false calls assert_false_
asserttrue calls obsolete_assert_true_logical_