run_test_case_named_ – naturalFRUIT
run_test_case_named_ Subroutine
23 statements
Source File
private subroutine run_test_case_named_(tc, tc_name)
reset linechar_count for each test case. ! "case_passed" is true here. ! "case_passed" becomes .false. at the first fail of assertion
Arguments
Type Intent Optional Attributes Name
public subroutine tc()
Arguments None
character(len=*), intent(in) :: tc_name
Calls
Called by
Contents
Source Code
run_test_case_named_
Source Code
  subroutine run_test_case_named_( tc, tc_name )
    interface
       subroutine tc()
       end subroutine
    end interface
    character(*), intent(in) :: tc_name
    integer :: initial_failed_assert_count
    initial_failed_assert_count = failed_assert_count
    ! Set the name of the unit test
    call set_case_name( tc_name )
    last_passed = .true.
    case_passed = .true.
    linechar_count = 0  !! reset linechar_count for each test case.
    message_index_from = message_index
    call system_clock(case_time_from)
    !$OMP BARRIER
    !!! "case_passed" is true here.
    !!! "case_passed" becomes .false. at the first fail of assertion
    call tc()
    !$OMP BARRIER
    if ( initial_failed_assert_count .eq. failed_assert_count ) then
       ! If no additional assertions failed during the run of this test case
       ! then the test case was successful
       successful_case_count = successful_case_count+1
    else
       failed_case_count = failed_case_count+1
    end if
    testCaseIndex = testCaseIndex+1
    ! Reset the name of the unit test back to the default
    call set_case_name( DEFAULT_CASE_NAME )
  end subroutine run_test_case_named_
Call graph
run_test_case_named_ calls set_case_name
set_case_name calls set_case_name_
set_case_name_ calls strip
strip calls strip_, strip_length_
runtestcase calls run_test_case_named_, run_test_case_
run_test_case_ calls run_test_case_named_
run_test_case calls run_test_case_named_, run_test_case_