set_case_name_ – naturalFRUIT
set_case_name_ Subroutine
4 statements
Source File
private subroutine set_case_name_(value)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: value
Calls
Called by
Contents
Source Code
set_case_name_
Source Code
  subroutine set_case_name_(value)
    character(*), intent(in) :: value
    case_name = strip(value, MSG_LENGTH)
  end subroutine set_case_name_
Call graph
set_case_name_ calls strip
strip calls strip_, strip_length_
set_case_name calls set_case_name_
set_unit_name calls set_case_name_
run_test_case_named_ calls set_case_name
run_test_case_ calls run_test_case_named_
run_test_case calls run_test_case_named_, run_test_case_
runtestcase calls run_test_case_named_, run_test_case_