strip_length_ – naturalFRUIT
strip_length_ Function
7 statements
Source File
private function strip_length_(value, length)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: value
integer, intent(in) :: length
Return Value character(len=length)
Called by
Contents
Source Code
strip_length_
Source Code
  function strip_length_(value, length)
    implicit none
    character(len=*), intent(in) :: value
    integer, intent(in) :: length
    character(len= length):: strip_length_
    strip_length_ = trim(adjustl(value))
  end function strip_length_
Call graph
strip calls strip_length_
fruit_summary_ calls strip
assert_eq_2d_string_ calls strip
assert_not_equals_2d_string_ calls strip
get_messages_ calls strip
case_failed_xml_ calls strip
assert_not_equals_1d_string_ calls strip
get_message_array_ calls strip
get_case_name_ calls strip
set_case_name_ calls strip
get_last_message calls strip
assert_eq_1d_string_ calls strip
assert_eq_string_ calls strip
assert_not_equals_string_ calls strip
make_error_msg_ calls strip
get_case_name calls get_case_name_
failed_assert_action calls make_error_msg_
case_failed_xml calls case_failed_xml_
assert_not_equals calls assert_not_equals_2d_string_, assert_not_equals_1d_string_, assert_not_equals_string_
set_case_name calls set_case_name_
get_message_array calls get_message_array_
assertnotequals calls assert_not_equals_2d_string_, assert_not_equals_1d_string_, assert_not_equals_string_
assert_equals calls assert_eq_2d_string_, assert_eq_1d_string_, assert_eq_string_
set_unit_name calls set_case_name_
obsolete_gettestsummary_ calls fruit_summary_
fruit_summary calls fruit_summary_
get_unit_name calls get_case_name_
get_messages calls get_messages_
assertequals calls assert_eq_2d_string_, assert_eq_1d_string_, assert_eq_string_
gettestsummary calls obsolete_gettestsummary_
add_fail_ calls failed_assert_action
run_test_case_named_ calls set_case_name
fruit_summary_mpi_ calls get_message_array
runtestcase calls run_test_case_named_, run_test_case_
add_fail calls add_fail_, add_fail_unit_
add_fail_unit_ calls add_fail_
run_test_case_ calls run_test_case_named_
run_test_case calls run_test_case_named_, run_test_case_
fruit_summary_mpi calls fruit_summary_mpi_
addfail calls add_fail_, add_fail_unit_