to_s_int_ – naturalFRUIT
to_s_int_ Function
8 statements
Source File
private function to_s_int_(value)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: value
Return Value character(len=500)
Called by
Contents
Source Code
to_s_int_
Source Code
  function to_s_int_ (value)
    implicit none
    character(len=500):: to_s_int_
    integer, intent(in) :: value
    character(len=500) :: result
    write (result, *) value
    to_s_int_ = adjustl(trim(result))
  end function to_s_int_
Call graph
to_s calls to_s_int_
assert_not_equals_double_ calls to_s
assert_eq_2d_double_ calls to_s
assert_eq_logical_ calls to_s
assert_false_ calls to_s
assert_not_equals_2d_complex_ calls to_s
assert_eq_1d_real_ calls to_s
assert_eq_1d_logical_ calls to_s
assert_eq_2d_string_ calls to_s
assert_eq_2d_int_ calls to_s
assert_eq_1d_double_ calls to_s
assert_eq_complex_ calls to_s
assert_eq_1d_double_in_range_ calls to_s
assert_eq_2d_complex_ calls to_s
assert_eq_1d_real_in_range_ calls to_s
assert_not_equals_1d_real_ calls to_s
assert_not_equals_2d_logical_ calls to_s
assert_not_equals_logical_ calls to_s
assert_not_equals_1d_logical_ calls to_s
assert_eq_1d_string_ calls to_s
assert_eq_complex_in_range_ calls to_s
assert_not_equals_real_ calls to_s
assert_eq_double_ calls to_s
assert_not_equals_2d_real_in_range_ calls to_s
assert_eq_string_ calls to_s
assert_not_equals_complex_in_range_ calls to_s
assert_not_equals_2d_string_ calls to_s
assert_not_equals_complex_ calls to_s
assert_not_equals_2d_int_ calls to_s
assert_not_equals_2d_complex_in_range_ calls to_s
assert_eq_real_in_range_ calls to_s
assert_eq_2d_logical_ calls to_s
assert_not_equals_1d_double_ calls to_s
assert_not_equals_1d_string_ calls to_s
assert_eq_int_ calls to_s
assert_eq_2d_complex_in_range_ calls to_s
assert_not_equals_1d_complex_ calls to_s
assert_not_equals_1d_complex_in_range_ calls to_s
assert_not_equals_int_ calls to_s
assert_eq_1d_complex_ calls to_s
assert_eq_1d_int_ calls to_s
assert_not_equals_string_ calls to_s
assert_not_equals_2d_real_ calls to_s
assert_not_equals_1d_real_in_range_ calls to_s
assert_not_equals_2d_double_in_range_ calls to_s
assert_eq_1d_complex_in_range_ calls to_s
assert_not_equals_1d_int_ calls to_s
assert_eq_real_ calls to_s
assert_not_equals_1d_double_in_range_ calls to_s
assert_not_equals_2d_double_ calls to_s
assert_eq_2d_real_in_range_ calls to_s
assert_eq_2d_real_ calls to_s
assert_true calls to_s
assert_not_equals_real_in_range_ calls to_s
assert_eq_double_in_range_ calls to_s
assert_not_equals_double_in_range_ calls to_s
assert_eq_2d_double_in_range_ calls to_s
assert_equals calls assert_eq_2d_double_, assert_eq_logical_, assert_eq_1d_real_, assert_eq_1d_logical_, assert_eq_2d_string_, assert_eq_2d_int_, assert_eq_1d_double_, assert_eq_complex_, assert_eq_1d_double_in_range_, assert_eq_2d_complex_, assert_eq_1d_real_in_range_, assert_eq_1d_string_, assert_eq_complex_in_range_, assert_eq_double_, assert_eq_string_, assert_eq_real_in_range_, assert_eq_2d_logical_, assert_eq_int_, assert_eq_2d_complex_in_range_, assert_eq_1d_complex_, assert_eq_1d_int_, assert_eq_1d_complex_in_range_, assert_eq_real_, assert_eq_2d_real_in_range_, assert_eq_2d_real_, assert_eq_double_in_range_, assert_eq_2d_double_in_range_
assertequals calls assert_eq_2d_double_, assert_eq_logical_, assert_eq_1d_real_, assert_eq_1d_logical_, assert_eq_2d_string_, assert_eq_2d_int_, assert_eq_1d_double_, assert_eq_complex_, assert_eq_1d_double_in_range_, assert_eq_2d_complex_, assert_eq_1d_real_in_range_, assert_eq_1d_string_, assert_eq_complex_in_range_, assert_eq_double_, assert_eq_string_, assert_eq_real_in_range_, assert_eq_2d_logical_, assert_eq_int_, assert_eq_2d_complex_in_range_, assert_eq_1d_complex_, assert_eq_1d_int_, assert_eq_1d_complex_in_range_, assert_eq_real_, assert_eq_2d_real_in_range_, assert_eq_2d_real_, assert_eq_double_in_range_, assert_eq_2d_double_in_range_
obsolete_assert_true_logical_ calls assert_true
assert_not_equals calls assert_not_equals_double_, assert_not_equals_2d_complex_, assert_not_equals_1d_real_, assert_not_equals_2d_logical_, assert_not_equals_logical_, assert_not_equals_1d_logical_, assert_not_equals_real_, assert_not_equals_2d_real_in_range_, assert_not_equals_complex_in_range_, assert_not_equals_2d_string_, assert_not_equals_complex_, assert_not_equals_2d_int_, assert_not_equals_2d_complex_in_range_, assert_not_equals_1d_double_, assert_not_equals_1d_string_, assert_not_equals_1d_complex_, assert_not_equals_1d_complex_in_range_, assert_not_equals_int_, assert_not_equals_string_, assert_not_equals_2d_real_, assert_not_equals_1d_real_in_range_, assert_not_equals_2d_double_in_range_, assert_not_equals_1d_int_, assert_not_equals_1d_double_in_range_, assert_not_equals_2d_double_, assert_not_equals_real_in_range_, assert_not_equals_double_in_range_
assertnotequals calls assert_not_equals_double_, assert_not_equals_2d_complex_, assert_not_equals_1d_real_, assert_not_equals_2d_logical_, assert_not_equals_logical_, assert_not_equals_1d_logical_, assert_not_equals_real_, assert_not_equals_2d_real_in_range_, assert_not_equals_complex_in_range_, assert_not_equals_2d_string_, assert_not_equals_complex_, assert_not_equals_2d_int_, assert_not_equals_2d_complex_in_range_, assert_not_equals_1d_double_, assert_not_equals_1d_string_, assert_not_equals_1d_complex_, assert_not_equals_1d_complex_in_range_, assert_not_equals_int_, assert_not_equals_string_, assert_not_equals_2d_real_, assert_not_equals_1d_real_in_range_, assert_not_equals_2d_double_in_range_, assert_not_equals_1d_int_, assert_not_equals_1d_double_in_range_, assert_not_equals_2d_double_, assert_not_equals_real_in_range_, assert_not_equals_double_in_range_
assert_false calls assert_false_
asserttrue calls obsolete_assert_true_logical_