assert_not_equals – naturalFRUIT
assert_not_equals Interface
29 statements
Source File
public interface assert_not_equals
Calls
Contents
Module Procedures
assert_not_equals_logical_ assert_not_equals_1d_logical_ assert_not_equals_2d_logical_ assert_not_equals_string_ assert_not_equals_1d_string_ assert_not_equals_2d_string_ assert_not_equals_int_ assert_not_equals_1d_int_ assert_not_equals_2d_int_ assert_not_equals_real_ assert_not_equals_real_in_range_ assert_not_equals_1d_real_ assert_not_equals_1d_real_in_range_ assert_not_equals_2d_real_ assert_not_equals_2d_real_in_range_ assert_not_equals_double_ assert_not_equals_double_in_range_ assert_not_equals_1d_double_ assert_not_equals_1d_double_in_range_ assert_not_equals_2d_double_ assert_not_equals_2d_double_in_range_ assert_not_equals_complex_ assert_not_equals_complex_in_range_ assert_not_equals_1d_complex_ assert_not_equals_1d_complex_in_range_ assert_not_equals_2d_complex_ assert_not_equals_2d_complex_in_range_
Module Procedures
private subroutine assert_not_equals_logical_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: var1
logical, intent(in) :: var2
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_logical_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: var1(n)
logical, intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_logical_(var1, var2, n, m, message)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: var1(n,m)
logical, intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_string_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var1
character(len=*), intent(in) :: var2
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_string_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var1(n)
character(len=*), intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_string_(var1, var2, n, m, message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var1(n,m)
character(len=*), intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_int_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: var1
integer, intent(in) :: var2
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_int_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: var1(n)
integer, intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_int_(var1, var2, n, m, message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: var1(n,m)
integer, intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_real_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1
real, intent(in) :: var2
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_real_in_range_(var1, var2, delta, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1
real, intent(in) :: var2
real, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_real_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1(n)
real, intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_real_in_range_(var1, var2, n, delta, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1(n)
real, intent(in) :: var2(n)
integer, intent(in) :: n
real, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_real_(var1, var2, n, m, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1(n,m)
real, intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_real_in_range_(var1, var2, n, m, delta, message)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var1(n,m)
real, intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
real, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_double_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: var1
double precision, intent(in) :: var2
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_double_in_range_(var1, var2, delta, message)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: var1
double precision, intent(in) :: var2
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_double_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: var1(n)
double precision, intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_double_in_range_(var1, var2, n, delta, message)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: var1(n)
double precision, intent(in) :: var2(n)
integer, intent(in) :: n
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_double_(var1, var2, n, m, message)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: var1(n,m)
double precision, intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_double_in_range_(var1, var2, n, m, delta, message)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: var1(n,m)
double precision, intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_complex_(var1, var2, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1
complex(kind=kind(1.0D0)), intent(in) :: var2
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_complex_in_range_(var1, var2, delta, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1
complex(kind=kind(1.0D0)), intent(in) :: var2
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_complex_(var1, var2, n, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1(n)
complex(kind=kind(1.0D0)), intent(in) :: var2(n)
integer, intent(in) :: n
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_1d_complex_in_range_(var1, var2, n, delta, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1(n)
complex(kind=kind(1.0D0)), intent(in) :: var2(n)
integer, intent(in) :: n
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_complex_(var1, var2, n, m, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1(n,m)
complex(kind=kind(1.0D0)), intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in), optional :: message
private subroutine assert_not_equals_2d_complex_in_range_(var1, var2, n, m, delta, message)
Arguments
Type Intent Optional Attributes Name
complex(kind=kind(1.0D0)), intent(in) :: var1(n,m)
complex(kind=kind(1.0D0)), intent(in) :: var2(n,m)
integer, intent(in) :: n
integer, intent(in) :: m
double precision, intent(in) :: delta
character(len=*), intent(in), optional :: message
Call graph
assert_not_equals calls assert_not_equals_double_, assert_not_equals_2d_complex_, assert_not_equals_2d_double_in_range_, assert_not_equals_1d_real_, assert_not_equals_2d_logical_, assert_not_equals_logical_, assert_not_equals_1d_logical_, assert_not_equals_real_, assert_not_equals_2d_real_in_range_, assert_not_equals_complex_in_range_, assert_not_equals_2d_string_, assert_not_equals_complex_, assert_not_equals_2d_int_, assert_not_equals_2d_complex_in_range_, assert_not_equals_1d_double_, assert_not_equals_1d_complex_, assert_not_equals_1d_string_, assert_not_equals_1d_complex_in_range_, assert_not_equals_int_, assert_not_equals_string_, assert_not_equals_2d_real_, assert_not_equals_1d_real_in_range_, assert_not_equals_1d_int_, assert_not_equals_1d_double_in_range_, assert_not_equals_2d_double_, assert_not_equals_real_in_range_, assert_not_equals_double_in_range_
assert_not_equals_double_ calls to_s, add_success
assert_not_equals_2d_complex_ calls to_s, add_success
assert_not_equals_2d_double_in_range_ calls to_s, add_success
assert_not_equals_1d_real_ calls to_s, add_success
assert_not_equals_2d_logical_ calls to_s, add_success
assert_not_equals_logical_ calls to_s, add_success
assert_not_equals_1d_logical_ calls to_s, add_success
assert_not_equals_real_ calls to_s, add_success
assert_not_equals_2d_real_in_range_ calls to_s, add_success
assert_not_equals_complex_in_range_ calls to_s, add_success
assert_not_equals_2d_string_ calls to_s, strip, add_success
assert_not_equals_complex_ calls to_s, add_success
assert_not_equals_2d_int_ calls to_s, add_success
assert_not_equals_2d_complex_in_range_ calls to_s, add_success
assert_not_equals_1d_double_ calls to_s, add_success
assert_not_equals_1d_complex_ calls to_s, add_success
assert_not_equals_1d_string_ calls to_s, strip, add_success
assert_not_equals_1d_complex_in_range_ calls to_s, add_success
assert_not_equals_int_ calls to_s, add_success
assert_not_equals_string_ calls to_s, strip, add_success
assert_not_equals_2d_real_ calls to_s, add_success
assert_not_equals_1d_real_in_range_ calls to_s, add_success
assert_not_equals_1d_int_ calls to_s, add_success
assert_not_equals_1d_double_in_range_ calls to_s, add_success
assert_not_equals_2d_double_ calls to_s, add_success
assert_not_equals_real_in_range_ calls to_s, add_success
assert_not_equals_double_in_range_ calls to_s, add_success
to_s calls to_s_int_, to_s_string_, to_s_complex_, to_s_real_, to_s_logical_, to_s_double_, to_s_double_complex_
strip calls strip_, strip_length_
add_success calls success_mark_
success_mark_ calls output_mark_