equals – naturalFRUIT
equals Interface
8 statements
Source File
public interface equals
Calls
Contents
Module Procedures
equalEpsilon floatEqual integerEqual doublePrecisionEqual stringEqual logicalEqual
Module Procedures
private function equalEpsilon(number1, number2, epsilon) result(resultValue)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: number1
real, intent(in) :: number2
real, intent(in) :: epsilon
Return Value logical
private function floatEqual(number1, number2) result(resultValue)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: number1
real, intent(in) :: number2
Return Value logical
private function integerEqual(number1, number2) result(resultValue)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: number1
integer, intent(in) :: number2
Return Value logical
private function doublePrecisionEqual(number1, number2) result(resultValue)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: number1
double precision, intent(in) :: number2
Return Value logical
private function stringEqual(str1, str2) result(resultValue)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str1
character(len=*), intent(in) :: str2
Return Value logical
private function logicalEqual(l1, l2) result(resultValue)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: l1
logical, intent(in) :: l2
Return Value logical
Call graph
equals calls doubleprecisionequal, stringequal, integerequal, logicalequal, equalepsilon, floatequal