get_message_array – naturalFRUIT
get_message_array Interface
3 statements
Source File
public interface get_message_array
Calls
Called by
Contents
Module Procedures
get_message_array_
Module Procedures
private subroutine get_message_array_(msgs)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(out) :: msgs(:)
Call graph
get_message_array calls get_message_array_
get_message_array_ calls strip
strip calls strip_, strip_length_
fruit_summary_mpi_ calls get_message_array
fruit_summary_mpi calls fruit_summary_mpi_