getTestSummary – naturalFRUIT
getTestSummary Interface
3 statements
Source File
public interface getTestSummary
Calls
Contents
Module Procedures
obsolete_getTestSummary_
Module Procedures
private subroutine obsolete_getTestSummary_()
Arguments
None
Call graph
gettestsummary calls obsolete_gettestsummary_
obsolete_gettestsummary_ calls fruit_summary_, obsolete_
fruit_summary_ calls strip, fruit_summary_table_
strip calls strip_, strip_length_