runTestCase – naturalFRUIT
runTestCase Interface
4 statements
Source File
public interface runTestCase
Calls
Contents
Module Procedures
run_test_case_ run_test_case_named_
Module Procedures
private subroutine run_test_case_(tc)
Arguments
Type Intent Optional Attributes Name
public subroutine tc()
Arguments None
private subroutine run_test_case_named_(tc, tc_name)
reset linechar_count for each test case. ! "case_passed" is true here. ! "case_passed" becomes .false. at the first fail of assertion
Arguments
Type Intent Optional Attributes Name
public subroutine tc()
Arguments None
character(len=*), intent(in) :: tc_name
Call graph
runtestcase calls run_test_case_named_, run_test_case_
run_test_case_named_ calls set_case_name
run_test_case_ calls run_test_case_named_
set_case_name calls set_case_name_
set_case_name_ calls strip
strip calls strip_, strip_length_